# Generated by Django 5.0.2 on 2024-02-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('date_nasc', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=50)),
                ('date_contrato', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_funcionarios', to='Users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=6)),
                ('devedor', models.BooleanField()),
                ('saldo', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_aluno', to='Users.users')),
            ],
        ),
    ]
