# Generated by Django 5.0.2 on 2024-02-20 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IES', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='name',
            new_name='curso',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='year',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='setor_funcionario', to='IES.setor'),
        ),
        migrations.AddField(
            model_name='users',
            name='cidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='endereco',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
