# Generated by Django 5.0.2 on 2024-02-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IES',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.CharField(max_length=200)),
                ('ies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setor_ies', to='IES.ies')),
            ],
        ),
    ]
