# Generated by Django 5.0.2 on 2024-02-25 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0005_delete_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_rate', models.FloatField(null=True)),
                ('loan_created_at', models.DateTimeField(auto_now_add=True)),
                ('name_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_loans', to='Book.book')),
                ('name_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
