# Generated by Django 5.0.2 on 2024-02-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=200)),
                ('data_pub', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='media/')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genero_livro', to='Livros.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateField()),
                ('prazo', models.CharField(max_length=200)),
                ('taxaMulta', models.CharField(max_length=200)),
                ('data_devolucao', models.DateField()),
                ('multa', models.CharField(max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aluno_emprestimo', to='Users.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livro_emprestimo', to='Livros.livros')),
            ],
        ),
    ]
