# Generated by Django 5.0.2 on 2024-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='data_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_pub',
            field=models.DateField(),
        ),
    ]
