# Generated by Django 5.0.2 on 2024-02-23 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publishing_company', models.CharField(max_length=200)),
                ('edition', models.CharField(max_length=50)),
                ('price_loan', models.FloatField()),
                ('photo', models.ImageField(upload_to='media')),
                ('date_published', models.DateField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_genre', to='Book.genre')),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_rate', models.FloatField()),
                ('loan_created_at', models.DateTimeField(auto_now_add=True)),
                ('name_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_loans', to='Book.book')),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
