# Generated by Django 5.0.2 on 2024-02-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_loan_name_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loan',
        ),
    ]
