# Generated by Django 5.0.2 on 2024-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_delete_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
